ALTER TABLE tasks ADD COLUMN start_date TEXT DEFAULT NULL;
ALTER TABLE tasks ADD COLUMN due_date TEXT DEFAULT NULL;
ALTER TABLE tasks ADD COLUMN completed_at TEXT DEFAULT NULL;
ALTER TABLE tasks ADD COLUMN rrule TEXT DEFAULT NULL;
