export default {
    VIEWS__AUTH_WELCOME: ", and welcome to sisyphus.",
    VIEWS__AUTH_HAPPY: "we are happy that you are here;",
    VIEWS__AUTH_PLEASE: "please, ",
    VIEWS__AUTH_SELECT: "open",
    VIEWS__AUTH_CREATE: "create",
    VIEWS__AUTH_WORKSPACE: " a workspace",
    VIEWS__AUTH_DATA: "your data never leaves your device.",
    VIEWS__AUTH_MALFORM_HEAD: "Could not open workspace",
    VIEWS__AUTH_MALFORM_SUBHEAD: "Please check that the file exists and is a valid database.",

    VIEWS__EDITOR_PLACEHOLDER: "start typing...",

    VIEWS__AUTH_LOGOUT_CONFIRM: "Are you sure you want to close this workspace?",

    COMPONENTS__RRULEMODAL_REPEAT: "Repeat...",
    COMPONENTS__RRULEMODAL_EVERY: "every so often",
    COMPONENTS__RRULEMODAL_NONE: "no repeating rule",
    COMPONENTS__DATEMODAL_START: "Start date",
    COMPONENTS__DATEMODAL_DUE: "Due date",
    COMPONENTS__DATEPICKER_TIME: "Time...",
    COMPONENTS__DATEPICKER_DATETIME: "Date or time...",
    VIEWS__EDITOR_EXIT_FOCUS: "Exit Focus",
    VIEWS__EDITOR_FIND: "find...",
    VIEWS__DEBUG_TITLE: "Scheduler Debug",
    VIEWS__DEBUG_CTA: "Inspect",
    VIEWS__DEBUG_HINT: "how the scheduler assigns tasks, resolves conflicts, and uses your preferences.",
    VIEWS__DEBUG_LOADING: "Computing schedule...",
    VIEWS__DEBUG_RESOLVE: "Re-solve",
    VIEWS__DEBUG_SCHEDULE: "Schedule Grid",
    VIEWS__DEBUG_TASKS: "Task Diagnostics",
    VIEWS__DEBUG_DUALS: "Dual Variables",
    VIEWS__DEBUG_PARKED: "Parked Tasks",
    VIEWS__DEBUG_PARKED_HINT: "These tasks are optimally deferred — every chunk of time is better spent elsewhere.",
    VIEWS__BROWSE_PLACEHOLDER: "search tasks... %wildcards% and gap_ both works",
    VIEWS__BROWSE_EMPTY_PROMPT: "what would you like to find?",
    VIEWS__BROWSE_TOO_MANY: "{n} results — try being more specific.",
    VIEWS__BROWSE_NO_RESULTS: "no matches found",
    TOOLTIPS: {
        PLANNING: "Planning",
        ACTION: "Action",
        BROWSE: "Browse",
        COMPLETED: "Completed",
        SETTINGS: "Settings",
        TRAINING: "Training",
        DEBUG: "Debug",
        LOGOUT: "Logout",
        PREVIOUS_SHEET: "Previous Sheet",
        NEXT_SHEET: "Next Sheet",
        DEFER: "Defer",
        DUE: "Due",
        REPEAT: "Repeat",
        EFFORT: "Effort",
        COMPLETE: "Complete",
        START: "Start date",
        COLLAPSE: "Focus mode",
        ACTION_VISIT: "View in planning",
        ACTION_REPLY: "Reply to task",
        ACTION_SCHEDULE: "Schedule date",
        ACTION_LOCK: "Auto-schedule",
        ACTION_UNLOCK: "Auto-schedule",
        ACTION_EDIT: "Action (editable)",
        ACTION_DRAG: "Drag to reschedule",
    },

    CHUNK_LABELS: ["midnight", "dawn", "morning", "afternoon", "evening", "night"],
    VIEWS__SETTINGS_TITLE: "settings",
    VIEWS__SETTINGS_CALENDARS: "Calendars",
    VIEWS__SETTINGS_CALENDARS_HINT: "Add ICS calendar URLs. Events will reduce available scheduling capacity.",
    VIEWS__SETTINGS_ADD_CALENDAR: "add calendar",
    VIEWS__SETTINGS_TRAINING: "Model Training",
    VIEWS__SETTINGS_TRAINING_CTA: "Teach the scheduler",
    VIEWS__SETTINGS_TRAINING_HINT: "your weekly completion habits and tag vocabulary.",
    VIEWS__TRAINING_TITLE: "training",
    VIEWS__TRAINING_INPUT_PLACEHOLDER: "describe a task... @tag",
    VIEWS__TRAINING_TASKS_LABEL: "click a task, then click a time slot on the grid",
    VIEWS__TRAINING_GRID_LABEL: "weekly completion habits",
    VIEWS__TRAINING_INSTRUCTIONS: [
        "Type some example tasks with a @tag (e.g. \"review PRs @work\") and press enter. Then click each task and place it on the grid where you'd normally do it.",
        "Our algorithm will use the task names to automatically infer future tags so you don't have to type them, and use the inferred tags to learn your preferences for scheduling. As you complete more tasks this will become more accurate.",
    ],
    VIEWS__ACTION_OVERDUE: "Before today",
    VIEWS__ACTION_EMPTY: [
        "Nothing on the horizon. Have a beer, or",
        "All clear. Touch some grass, or",
        "Inbox zero, calendar zero. Enjoy it, or",
        "The boulder rests. Take a nap, or",
    ],
    VIEWS__ACTION_EMPTY_CTA: "plan something",
    TEMPORAL_GREETINGS: [
        "good morning",
        "good afternoon",
        "good evening"
    ],
    GREETINGS: [
        "hello",
        "howdy",
        "hi"
    ],
    SYNC_LOADING: "Loading...",
    SYNC_RESCHEDULING: "Globally rescheduling...",
    SYNC_QUOTES: [
        "one must imagine sisyphus happy",
        "the struggle itself toward the heights is enough to fill a man's heart",
        "in the middle of winter, I at last discovered that there was in me an invincible summer",
        "shall I apply myself to life or shall I apply myself to death",
        "we must learn to live with despair and still not give in to it",
        "there is no fate that cannot be surmounted by scorn",
        "the only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion",
        "I leave sisyphus at the foot of the mountain",
        "what is called a reason for living is also an excellent reason for dying",
        "you will never be happy if you continue to search for what happiness consists of",
        "always go too far, because that's where you'll find the truth",
        "real generosity toward the future lies in giving all to the present",
        "to be happy, we must not be too concerned with others",
        "I do not want to be a genius — I have enough problems just trying to be a man",
        "man is the only creature who refuses to be what he is",
        "at any street corner the feeling of absurdity can strike any man in the face",
    ],
};
