export default {
    VIEWS__AUTH_WELCOME: ", and welcome to sisyphus.",
    VIEWS__AUTH_HAPPY: "we are happy that you are here;",
    VIEWS__AUTH_PLEASE: "please, ",
    VIEWS__AUTH_SELECT: "open",
    VIEWS__AUTH_CREATE: "create",
    VIEWS__AUTH_WORKSPACE: " a workspace",
    VIEWS__AUTH_DATA: "your data stays local unless you enable sync.",
    VIEWS__AUTH_MALFORM_HEAD: "Could not open workspace",
    VIEWS__AUTH_MALFORM_SUBHEAD: "Please check that the file exists and is a valid database.",

    VIEWS__EDITOR_PLACEHOLDER: "start typing...",

    VIEWS__AUTH_LOGOUT_CONFIRM: "Are you sure you want to close this workspace?",

    COMPONENTS__RRULEMODAL_REPEAT: "Repeat...",
    COMPONENTS__RRULEMODAL_EVERY: "every so often",
    COMPONENTS__RRULEMODAL_NONE: "no repeating rule",
    COMPONENTS__DATEMODAL_START: "Start date",
    COMPONENTS__DATEMODAL_DUE: "Due date",
    COMPONENTS__DATEPICKER_TIME: "Time...",
    COMPONENTS__DATEPICKER_DATETIME: "Date or time...",
    VIEWS__EDITOR_EXIT_FOCUS: "Exit Focus",
    VIEWS__EDITOR_FIND: "find...",
    VIEWS__DEBUG_TITLE: "Scheduler Debug",
    VIEWS__DEBUG_CTA: "Inspect",
    VIEWS__DEBUG_HINT: "how the scheduler assigns tasks, resolves conflicts, and uses your preferences.",
    VIEWS__DEBUG_LOADING: "Computing schedule...",
    VIEWS__DEBUG_RESOLVE: "Re-solve",
    VIEWS__DEBUG_SCHEDULE: "Schedule Grid",
    VIEWS__DEBUG_TASKS: "Task Diagnostics",
    VIEWS__DEBUG_DUALS: "Dual Variables",
    VIEWS__DEBUG_PARKED: "Parked Tasks",
    VIEWS__DEBUG_PARKED_HINT: "These tasks are optimally deferred — every chunk of time is better spent elsewhere.",
    VIEWS__BROWSE_PLACEHOLDER: "search tasks... %wildcards% and gap_ both works",
    VIEWS__BROWSE_EMPTY_PROMPT: "what would you like to find?",
    VIEWS__BROWSE_TOO_MANY: "{n} results — try being more specific.",
    VIEWS__BROWSE_NO_RESULTS: "no matches found",
    TOOLTIPS: {
        PLANNING: "Planning",
        ACTION: "Action",
        BROWSE: "Browse",
        COMPLETED: "Completed",
        SETTINGS: "Settings",
        TRAINING: "Training",
        DEBUG: "Debug",
        LOGOUT: "Logout",
        PREVIOUS_SHEET: "Previous Sheet",
        NEXT_SHEET: "Next Sheet",
        DEFER: "Defer",
        DUE: "Due",
        REPEAT: "Repeat",
        EFFORT: "Effort",
        COMPLETE: "Complete",
        START: "Start date",
        COLLAPSE: "Focus mode",
        ACTION_VISIT: "View in planning",
        ACTION_REPLY: "Reply to task",
        ACTION_REPARENT: "Reparent under new task",
        ACTION_SCHEDULE: "Schedule date",
        ACTION_LOCK: "Auto-schedule",
        ACTION_UNLOCK: "Auto-schedule",
        ACTION_EDIT: "Action (editable)",
        ACTION_DRAG: "Drag to reschedule",
    },

    CHUNK_LABELS: ["midnight", "dawn", "morning", "afternoon", "evening", "night"],
    VIEWS__SETTINGS_TITLE: "settings",
    VIEWS__SETTINGS_REMOTE_SYNC: "Remote Sync",
    VIEWS__SETTINGS_REMOTE_SYNC_HINT: "Optional Postgres event log for syncing this workspace across devices.",
    VIEWS__SETTINGS_REMOTE_SYNC_PERIOD: "Sync every",
    VIEWS__SETTINGS_REMOTE_SYNC_SECONDS: "seconds",
    VIEWS__SETTINGS_CALENDARS: "Calendars",
    VIEWS__SETTINGS_CALENDARS_HINT: "Add ICS calendar URLs. Events will reduce available scheduling capacity.",
    VIEWS__SETTINGS_ADD_CALENDAR: "add calendar",
    VIEWS__SETTINGS_TRAINING: "Model Training",
    VIEWS__SETTINGS_TRAINING_CTA: "Teach the scheduler",
    VIEWS__SETTINGS_TRAINING_HINT: "your weekly completion habits and tag vocabulary.",
    VIEWS__TRAINING_TITLE: "training",
    VIEWS__TRAINING_INPUT_PLACEHOLDER: "describe a task... @tag",
    VIEWS__TRAINING_TASKS_LABEL: "click a task, then click a time slot on the grid",
    VIEWS__TRAINING_GRID_LABEL: "weekly completion habits",
    VIEWS__TRAINING_INSTRUCTIONS: [
        "Type some example tasks with a @tag (e.g. \"review PRs @work\") and press enter. Then click each task and place it on the grid where you'd normally do it.",
        "Our algorithm will use the task names to automatically infer future tags so you don't have to type them, and use the inferred tags to learn your preferences for scheduling. As you complete more tasks this will become more accurate.",
    ],
    VIEWS__ACTION_OVERDUE: "Before today",
    VIEWS__ACTION_EMPTY: [
        "Nothing on the horizon. Have a beer, or",
        "All clear. Touch some grass, or",
        "Inbox zero, calendar zero. Enjoy it, or",
        "The boulder rests. Take a nap, or",
    ],
    VIEWS__ACTION_EMPTY_CTA: "plan something",
    TEMPORAL_GREETINGS: [
        "good morning",
        "good afternoon",
        "good evening"
    ],
    GREETINGS: [
        "hello",
        "howdy",
        "hi"
    ],
    VIEWS__SETTINGS_GRID: "Schedule Grid",
    VIEWS__SETTINGS_GRID_HINT: "How the day is divided into chunks for scheduling.",
    VIEWS__SETTINGS_GRID_CHUNKS: "Chunks per day",
    VIEWS__SETTINGS_GRID_HORIZON: "Horizon (days)",
    VIEWS__SETTINGS_GRID_LABELS: "Chunk labels",
    VIEWS__SETTINGS_GRID_DERIVED: "hours/chunk, slots/chunk (1 slot = 30 min)",
    VIEWS__SETTINGS_GLOBAL_RESCHEDULE: "Global Reschedule",
    VIEWS__SETTINGS_GLOBAL_RESCHEDULE_HINT: "What to clean up before a manual reschedule.",
    VIEWS__SETTINGS_RESCHEDULE_MISSED_SCHEDULES: "Reschedule missed scheduled tasks",
    VIEWS__SETTINGS_RESCHEDULE_MISSED_SCHEDULES_HINT: "Clear past scheduled times for unlocked incomplete tasks before solving.",

    VIEWS__SETTINGS_TUTORIAL: "Tutorial",
    VIEWS__SETTINGS_TUTORIAL_CTA: "Take the tour",
    VIEWS__SETTINGS_TUTORIAL_HINT: "to learn how sisyphus works.",

    TOUR__WELCOME: "Welcome to sisyphus — a task manager that automatically schedules your work. Let's walk through how it works.",
    TOUR__PLANNING_NAV: "This is Planning — your main workspace. Every paragraph you type here is a task.",
    TOUR__PLANNING_EDITOR: "Just start typing. Press Enter to create new tasks. Indent with Tab to nest them under a parent.",
    TOUR__TASK_CHECK: "Click the circle to mark a task complete. Use Cmd+Enter as a shortcut.",
    TOUR__TASK_TOOLBAR: "Hover over a task to see its toolbar. These buttons control scheduling — due dates, start dates, effort, and recurrence.",
    TOUR__TASK_DUE: "Set a due date. The scheduler uses this to decide when to surface the task in your Action view.",
    TOUR__TASK_EFFORT: "Set estimated effort. This tells the scheduler how much time to allocate.",
    TOUR__TASK_REPEAT: "Set a recurrence rule — daily, weekly, etc. The task will regenerate after completion.",
    TOUR__TASK_REPLY: "Reply to a task to create a linked subtask. Replies appear as indented children with an arrow.",
    TOUR__TASK_FOCUS: "Focus mode collapses everything except this task and its children. Great for deep work.",
    TOUR__ACTION_NAV: "This is Action — your daily schedule. Tasks appear here automatically based on due dates, effort, and your habits.",
    TOUR__ACTION_VIEW: "Tasks are grouped by time of day. Drag them to reschedule. The scheduler fills gaps with work it thinks fits best.",
    TOUR__BROWSE_NAV: "Browse lets you search across all tasks. Use %wildcards% or gap_ patterns. Save searches as sheets for quick access.",
    TOUR__COMPLETED_NAV: "Completed shows your finished tasks. A record of everything you've done.",
    TOUR__SYNC: "This dot pulses when changes are syncing. Click it to force a global reschedule.",
    TOUR__SETTINGS_NAV: "Settings is where you add calendars, train the scheduler, and manage your workspace.",
    TOUR__DONE_MSG: "That's the basics. Write some tasks in Planning, set due dates, and watch them appear in Action. The more you use it, the smarter the scheduler gets.",
    TOUR__NEXT: "next",
    TOUR__BACK: "back",
    TOUR__DONE: "got it",

    SYNC_LOADING: "Loading...",
    SYNC_RESCHEDULING: "Globally rescheduling...",
    SYNC_QUOTES: [
        "one must imagine sisyphus happy",
        "the struggle itself toward the heights is enough to fill a man's heart",
        "in the middle of winter, I at last discovered that there was in me an invincible summer",
        "shall I apply myself to life or shall I apply myself to death",
        "we must learn to live with despair and still not give in to it",
        "there is no fate that cannot be surmounted by scorn",
        "the only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion",
        "I leave sisyphus at the foot of the mountain",
        "what is called a reason for living is also an excellent reason for dying",
        "you will never be happy if you continue to search for what happiness consists of",
        "always go too far, because that's where you'll find the truth",
        "real generosity toward the future lies in giving all to the present",
        "to be happy, we must not be too concerned with others",
        "I do not want to be a genius — I have enough problems just trying to be a man",
        "man is the only creature who refuses to be what he is",
        "at any street corner the feeling of absurdity can strike any man in the face",
    ],
};
