export default {
    VIEWS__AUTH_WELCOME: ", and welcome to sisyphus.",
    VIEWS__AUTH_HAPPY: "we are happy that you are here;",
    VIEWS__AUTH_PLEASE: "please, ",
    VIEWS__AUTH_SELECT: "open",
    VIEWS__AUTH_CREATE: "create",
    VIEWS__AUTH_WORKSPACE: " a workspace",
    VIEWS__AUTH_DATA: "your data never leaves your device.",
    VIEWS__AUTH_MALFORM_HEAD: "Could not open workspace",
    VIEWS__AUTH_MALFORM_SUBHEAD: "Please check that the file exists and is a valid database.",

    VIEWS__EDITOR_PLACEHOLDER: "start typing...",

    VIEWS__AUTH_LOGOUT_CONFIRM: "Are you sure you want to close this workspace?",

    COMPONENTS__RRULEMODAL_REPEAT: "Repeat...",
    COMPONENTS__RRULEMODAL_EVERY: "every so often",
    COMPONENTS__RRULEMODAL_NONE: "no repeating rule",
    COMPONENTS__DATEMODAL_START: "Start date",
    COMPONENTS__DATEMODAL_DUE: "Due date",
    COMPONENTS__DATEPICKER_TIME: "Time...",
    COMPONENTS__DATEPICKER_DATETIME: "Date or time...",
    VIEWS__EDITOR_EXIT_FOCUS: "Exit Focus",
    VIEWS__EDITOR_FIND: "find...",
    VIEWS__DEBUG_TITLE: "Scheduler Debug",
    VIEWS__DEBUG_LOADING: "Computing schedule...",
    VIEWS__DEBUG_RESOLVE: "Re-solve",
    VIEWS__DEBUG_SCHEDULE: "Schedule Grid",
    VIEWS__DEBUG_TASKS: "Task Diagnostics",
    VIEWS__DEBUG_DUALS: "Dual Variables",
    VIEWS__DEBUG_PARKED: "Parked Tasks",
    VIEWS__DEBUG_PARKED_HINT: "These tasks are optimally deferred — every chunk of time is better spent elsewhere.",
    VIEWS__BROWSE_PLACEHOLDER: "search tasks... %wildcards% and gap_ both works",
    VIEWS__BROWSE_EMPTY_PROMPT: "what would you like to find?",
    VIEWS__BROWSE_TOO_MANY: "{n} results — try being more specific.",
    VIEWS__BROWSE_NO_RESULTS: "no matches found, add one?",
    TOOLTIPS: {
        PLANNING: "Planning",
        ACTION: "Action",
        BROWSE: "Browse",
        COMPLETED: "Completed",
        SETTINGS: "Settings",
        TRAINING: "Training",
        DEBUG: "Debug",
        LOGOUT: "Logout",
        PREVIOUS_SHEET: "Previous Sheet",
        NEXT_SHEET: "Next Sheet",
        DEFER: "Defer",
        DUE: "Due",
        REPEAT: "Repeat",
        EFFORT: "Effort",
        COMPLETE: "Complete",
        START: "Start date",
        COLLAPSE: "Focus mode",
        ACTION_VISIT: "View in planning",
        ACTION_REPLY: "Reply to task",
        ACTION_SCHEDULE: "Set schedule date",
        ACTION_LOCK: "Auto-schedule",
        ACTION_UNLOCK: "Auto-schedule",
        ACTION_EDIT: "Action (editable)",
        ACTION_DRAG: "Drag to reschedule",
    },

    CHUNK_LABELS: ["midnight", "dawn", "morning", "afternoon", "evening", "night"],
    VIEWS__SETTINGS_TITLE: "settings",
    VIEWS__SETTINGS_CALENDARS: "Calendars",
    VIEWS__SETTINGS_CALENDARS_HINT: "Add ICS calendar URLs. Events will reduce available scheduling capacity.",
    VIEWS__SETTINGS_ADD_CALENDAR: "add calendar",
    VIEWS__SETTINGS_TRAINING: "Model Training",
    VIEWS__SETTINGS_TRAINING_HINT: "Teach the scheduler your energy patterns and tag vocabulary.",
    VIEWS__SETTINGS_OPEN_TRAINING: "open training",
    VIEWS__TRAINING_TITLE: "training",
    VIEWS__TRAINING_INPUT_PLACEHOLDER: "describe a task... @tag",
    VIEWS__TRAINING_TASKS_LABEL: "drag tasks to the grid",
    VIEWS__TRAINING_GRID_LABEL: "weekly energy pattern",
    VIEWS__TRAINING_EMPTY: "type a task above with an @tag, then drag it to a time slot",
    TEMPORAL_GREETINGS: [
        "good morning",
        "good afternoon",
        "good evening"
    ],
    GREETINGS: [
        "hello",
        "howdy",
        "hi"
    ],
};
